### ISSUE TITLE
Consider migrating from git-submodules to git-subtree?

### ISSUE THREAD

**Issue by crlf0710** [DiligentGraphics/DiligentEngine#156]
I feel git-subtree is more easy to work with.

**Comment by TheMostDiligent** [comment]
I honestly did not know about git subtrees. After reading about them a bit, I can't see what advantage they can give or how the project can be updated to use them at all.

**Comment by crlf0710** [comment]
Basically that would make this repository self-contained. From user's perspective, the github DiligentEngine repo's "Releases" automatic source code packaging will work. And also, user can git clone --depth=1 to retrieve a whole shallow copy of the whole repo.

From project maintainer's perspective, i agree it doesn't really bring benefit.

**Comment by TheMostDiligent** [comment]
> From user's perspective, the github DiligentEngine repo's "Releases" automatic source code packaging will work

Releases will still not work because there are third-party modules that are included as submodules. They will still be missing. There is a source code archive attached to the latest release that can be downloaded and is self-contained.

> And also, user can git clone --depth=1 to retrieve a whole shallow copy of the whole repo.

I don't think this is a huge benefit. 

Right now, core module can be cloned and used independently, and so are core+tools and core+tools+fx modules. One of our main clients use core+tools as they don't need anything else. Subtrees don't allow this as far as I can tell because they are just references to commits. So you will still have to get all code before referencing the required commits.
