### ISSUE TITLE
Render to multiple windows?

### ISSUE THREAD

**Issue by mctb32** [DiligentGraphics/DiligentEngine#17]
Couldn't find it in the documentation - is it possible to render into multiple windows with Diligent? The use case is games supporting systems with multiple displays, or game editor apps that need to render into multiple child windows (wxWidgets, QT, etc.).

**Comment by DiligentGraphics** [comment]
For the moment you can only create single swap chain. Supporting multiple swap chains though should not be a problem for Direct3D11, Direct3D12 and Vulkan backends.

**Comment by mctb32** [comment]
And how about switching the target window handle between frames? For editors, where performance is not critical, you could render one frame to one window, then switch and render another frame with a different camera setup to another window. Perhaps this would be easier than supporting simultaneous multiple swap chains? This should also work with OpenGL as far as I know.

**Comment by DiligentGraphics** [comment]
On Windows, to get a render target from HWND, you need to create a swap chain attached to that window (at least I do not know the other way). You cannot reattach existing swap chain to another window. In fact, it turned out that as long as you attach a swap chain to a window, something internally happens, and if you want to say switch to Vulkan, you need to destroy and create a new window. Simply destroying D3D swap chain and creating Vulkan swap chain for existing window does not work (nothing is rendered on the screen) as long as there was D3D swap chain.

As long as you get the a render target from the swap chain, you can switch them without limitations. Not sure how rendering to multiple windows works on Linux with OpenGL. With Vulkan that should also be "easy" (if that is even applicable to Vulkan) to do.

**Comment by DiligentGraphics** [comment]
Should not be messy at all in D3D11, D3D12, and Vulkan backends. In OpenGL everything is messy. Yes, I think this feature can be added to the common API. 
https://github.com/DiligentGraphics/DiligentCore/issues/35

**Comment by mctb32** [comment]
Great! Big thanks for putting this on your roadmap!
