### ISSUE TITLE
[Need Help] Few questions

### ISSUE THREAD

**Issue by Hideman85** [DiligentGraphics/DiligentEngine#22]
Hi, I would like to use your engine to develop a voxel game and I have few questions about it:

- What's DiligentEngine repo has more than DiligentCore for development? You added some samples and tutorials that's really great for learning, but is DiligentCore is enough for development and compiling?

- How compile on windows with Mingw64 and without Visual Studio?

- How cross compile on linux for windows using also Mingw64?
I just use this for the moment but does not work because your cmake seems to not setup sources for external libs:
```
# the name of the target operating system
set(CMAKE_SYSTEM_NAME Windows)

# Which compilers to use for C and C++
set(CMAKE_C_COMPILER /usr/bin/x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/x86_64-w64-mingw32-g++)
```
```
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-w64-mingw32-g++
-- Check for working CXX compiler: /usr/bin/x86_64-w64-mingw32-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Target platform: Win32. SDK Version: 
D3D11_SUPPORTED: TRUE
D3D12_SUPPORTED: TRUE
GL_SUPPORTED: TRUE
GLES_SUPPORTED: FALSE
VULKAN_SUPPORTED: TRUE
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
-- Configuring done
CMake Error at DiligentCore/External/SPIRV-Cross/CMakeLists.txt:27 (add_library):
  Cannot find source file:

    readme.md

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at Projects/Asteroids/CMakeLists.txt:81 (add_executable):
  Cannot find source file:

    readme.md

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at DiligentCore/External/SPIRV-Cross/CMakeLists.txt:27 (add_library):
  No SOURCES given to target: SPIRVCross


CMake Error at Projects/Asteroids/CMakeLists.txt:81 (add_executable):
  No SOURCES given to target: Asteroids


-- Build files have been written to: DiligentEngine/build
```

- Do you use a specific lib for GUI rendering?

Thanks in advance for your further response.

**Comment by DiligentGraphics** [comment]
Hello, please find some answers below:

* Please note that Diligent Engine is a low-level graphics library, but not a full-featured game engine like Godot for instance. So if this is what you are looking for, Diligent would not fit your needs.

* Honestly, I've never worked with Mingw64. On Windows, I would highly recommend using native MSVC and MSBuild because D3D11 and D3D12 backends have many dependencies on libraries that come wirh Visual Studio distribution, and I do not know how to resolve them in Mingw64. You can build Core DLLs using MSBuild and then use them in your project.

* Cross-compiling for Windows on Linux is a rabbit hole that I do not really want to enter. If you know how to do this for graphics applications that use Direct3D11/12, this should work for Diligent too. But as I said, I do not know how to properly setup Windows build toolchain on Linux.  

* The repo has all the references to external repos, but you need to use `git clone --recursive` to get them:

`git clone --recursive https://github.com/DiligentGraphics/DiligentEngine.git`

* For GUI I use [AntTweakBar](http://anttweakbar.sourceforge.net/doc/), but I would not recommend sticking to it as it is not being developed/supported anymore.

**Comment by DiligentGraphics** [comment]
FYI, Mingw64 is now supported (e1d6dc27ec013dfecde942c7690432925ce3e23a).

**Comment by DiligentGraphics** [comment]
Closing this issue. Please feel free to reopen/create a new one if you have other questions
