### ISSUE TITLE
erroneous debug assert

### ISSUE THREAD

**Issue by yibbidy** [DiligentGraphics/DiligentEngine#46]
this seems minor.  I modified tutorial01 hello triangle to spin the triangle.  It runs fine but Debug output for Vulkan back end says:
Diligent Engine: ERROR in Diligent::DeviceContextVkImpl::CommitVkVertexBuffers() (DeviceContextVkImpl.cpp, 313): Currently bound pipeline state 'Simple triangle PSO' expects 1 input buffer slots, but only 0 is bound
and for GL back end:
Diligent Engine: ERROR: Debug assertion failed in Diligent::VAOCache::GetVAO(), file VAOCache.cpp, line 103:
Input layout requires more buffers than bound to the pipeline

I think the issue is that the example *doesn't* use a buffer for the vertex data -- it uses gl_VertexID as an index into some data defined in the vertex shader -- but my addition *does* use a buffer for the time parameter (UBO).  Looks like if there are any buffers in use then it is assumed one of them must be for vertex data:

assert comes from VAOCache.cpp in GL:
```
 {
        auto LayoutIt = LayoutElems;
        for (size_t Elem = 0; Elem < NumElems; ++Elem, ++LayoutIt)
        {
            auto BuffSlot = LayoutIt->BufferSlot;
            if (BuffSlot >= NumVertexStreams)
            {
                UNEXPECTED("Input layout requires more buffers than bound to the pipeline");
                continue;
            }
```

or maybe i'm doing it wrong.  attached modified tutorial01 files

**Comment by yibbidy** [comment]
[src.zip](https://github.com/DiligentGraphics/DiligentEngine/files/3305442/src.zip)

**Comment by DiligentGraphics** [comment]
The assertion is correct. When creating the pipeline state, you define one input vertex buffer:

```cpp
LayoutElement layoutElements[] =
{
	LayoutElement(2, 0, 1, VT_FLOAT32, False)
};
PSODesc.GraphicsPipeline.InputLayout.LayoutElements = layoutElements;
PSODesc.GraphicsPipeline.InputLayout.NumElements = _countof(layoutElements);
```

but never bind any. The engine checks that you bind the buffer when issuing a draw command at run time. Since you don't really use any vertex buffers, you don't need to define any layout elements and simply deleting the lines above fixes the problem and makes the tutorial run fine in both GL and Vulkan modes. 

I guess you confused uniform/constant buffer with vertex buffer. `InputLayout` is only used for vertex buffers to tell the system how to read data from the buffers. Uniform buffers should not be specified in the layout.

**Comment by yibbidy** [comment]
I see.  Thanks for the clarification.
