### ISSUE TITLE
Map/Unmap of vertex/index buffers is not thread safe 

### ISSUE THREAD

**Issue by TomasArce** [DiligentGraphics/DiligentEngine#72]
I am running multiple threads filling buffers with vertices and indices. I am running DX12, but probably other APIs will have the same problem... The problem seems to be with the allocator not been thread-safe. Maybe it should have a lock there? Anyways currently chasing my app and it seems like it should be an important feature to have in your engine.

Cheers,
Tomas

**Comment by DiligentGraphics** [comment]
Can you clarify a bit what the problem is. How do you fill multiple buffers from multiple threads: 
- What kind of buffers do you use (dynamic, static, default)
- How you write data to the buffers (Map, UpdateBuffer)
- Do you use separate deferred context in each thread

Tutorials 06, 09 and 10 all write data to GPU buffers from multiple threads without any problems.

**Comment by TomasArce** [comment]
My fault, I was not using the deferred context. All working now.
