### ISSUE TITLE
Is there a convention (for coordinate systems) for different backends? 

### ISSUE THREAD

**Issue by carlcc** [DiligentGraphics/DiligentEngine#75]
Hi,

   As we all known the, DX, OGL and Vulkan have different NDC.

   So what is the NDC of DG? Is there a unified NDC for all backends, thus we can assum the NDC, and then DG will help us convert coordinates to those different NDC of all different backends? Or we must handle different NDC manually?

Regards.

**Comment by TheMostDiligent** [comment]
Diligent uses Direct3D-style coordinate system. Vulkan allows negative viewport height, which makes it possible to make Vulkan backend 100% compatible with Direct3D [by messing with viewport coordinates](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/src/DeviceContextVkImpl.cpp#L999). 
OpenGL as always is a headache. There are two issues:
1. The notorious [-1, +1] NDC z range. This cannot be fixed at the API level, as it needs to be baked into a projection matrix. Diligent's projection function [takes parameter](https://github.com/DiligentGraphics/DiligentCore/blob/master/Common/interface/BasicMath.hpp#L1340) that indicates if the matrix should be constructed for OpenGL. Note that there is an extension that allows using the normal [0, +1] z range, but Diligent does not implement it.
2. Direct3D inverts Y axis when converting from NDC to Window space while OpenGL does not. To alleviate this problem, Diligent's [SetViewport](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngine/interface/DeviceContext.h#L805) method takes the size of the render target. By default these are taken from the currently bound render target. OpenGL uses these to adjust [viewport coordinates](https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineOpenGL/src/DeviceContextGLImpl.cpp#L231) similar to Vulkan, however since viewport height can't be negative there are few cases when it does not quite work.

So the bottom line is that Direct3D-style coordinates will work in majority of the situations. In few cases (such as rendering to a texture and then showing this texture on the screen), OpenGL may require special care: you may need to invert [V texture coordinate](https://github.com/DiligentGraphics/DiligentSamples/blob/master/Tutorials/Tutorial12_RenderTarget/assets/rendertarget.psh#L31). Other backends are always 100% consistent.

**Comment by carlcc** [comment]
Very helpful! Thank you!
